src/Application/MainBundle/Entity/Article.php
<?php

namespace Application\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Application\MainBundle\Entity\Article
 *
 * @ORM\Entity
 * @ORM\Table(name="article")
 * @ORM\Entity(repositoryClass="ArticleRepository")
 */
class Article {

    use ORMBehaviors\Translatable\Translatable,
        ORMBehaviors\Blameable\Blameable,
        ORMBehaviors\Timestampable\Timestampable,
        ORMBehaviors\SoftDeletable\SoftDeletable;

    public function __toString() {
        return $this->getTitle()? : '-';
    }

    public function getTitle() {
        return $this->translate()->getTitle();
    }

    public function getContent() {
        return $this->translate()->getContent();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="Author", mappedBy="articles", cascade={"persist"})
     */
    private $authors;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->authors = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add authors
     *
     * @param \Application\MainBundle\Entity\Author $authors
     * @return Article
     */
    public function addAuthor(\Application\MainBundle\Entity\Author $authors) {
        $authors->addArticle($this);
        $this->authors[] = $authors;

        return $this;
    }

    /**
     * Remove authors
     *
     * @param \Application\MainBundle\Entity\Author $authors
     */
    public function removeAuthor(\Application\MainBundle\Entity\Author $authors) {
        $authors->removeArticle($this);
        $this->authors->removeElement($authors);
    }

    /**
     * Get authors
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAuthors() {
        return $this->authors;
    }

}

src/Application/MainBundle/Controller/ArticleController.php
<?php

namespace Application\MainBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Security("has_role('ROLE_USER')")
 * @Route("/article")
 */
class ArticleController extends Controller {

    /**
     * @Route("/item/{id}", name="article.item", requirements={"id"="^[1-9]\d*$"})
     * @Template()
     */
    public function itemAction($id) {
        $query = $this->createQuery($id);
        $items = $query->getResult();

        if (count($items) !== 1) {
            throw $this->createNotFoundException();
        }

        $item = array_pop($items);
        
        return [
            'item' => $item,
        ];
    }

    /**
     * @Route("/list", name="article.list")
     * @Template()
     */
    public function listAction(Request $request) {
        $query = $this->createQuery();
        $page = $request->query->get('page', 1);
        $limit = $this->container->getParameter('pager_limit');
        $items = $this->get('knp_paginator')->paginate($query, $page, $limit);

        return [
            'items' => $items,
        ];
    }

    protected function createQuery($id = null) {
        $em = $this->getDoctrine()->getManager();
        $qb = $em->createQueryBuilder();

        $qb
                ->from('\Application\MainBundle\Entity\Article', 'a')
                ->leftJoin('a.authors', 'au')
                ->leftJoin('a.translations', 't')
                ->select('a, au, t')
        ;

        if ($id !== null) {
            $qb->andWhere('a.id = :id')->setParameter('id', $id);
        }

        $query = $qb->getQuery();

        return $query;
    }

}

src/Application/MainBundle/Resources/views/Article/item.html.twig
{% extends '::base.html.twig' %}

{% block content %}

    {% set authors = [] %}
    {% for a in item.authors %}
        {% set authors = authors|merge([ a.firstName~' '~a.lastName ]) %}
    {% endfor %}

    <h1 class="page-header">
        <i class="fa fa-copy text-muted"></i>
        {{ item.translate(app.request.locale).title }}

        <a class="btn btn-default pull-right" onclick="history.back()" title="{{ 'common.back_to_the_list'|trans }}">
            <i class="fa fa-arrow-left fa-lg"></i>
        </a>
    </h1>

    <div class="alert alert-info">
        <span>
            <i class="fa fa-edit fa-lg"></i>
            {{ authors|join(', ') }}
        </span>
        <span class="pull-right">
            <i class="fa fa-clock-o fa-lg"></i>
            {{ item.createdAt|date('Y-m-d H:i') }}
        </span>
    </div>

    <pre style="white-space: pre-wrap">{{ item.translate(app.request.locale).content|raw }}</pre>

{% endblock %}

src/Application/MainBundle/Resources/views/Article/list.html.twig
{% extends '::base.html.twig' %}

{% block content %}

    <h1 class="page-header">
        <i class="fa fa-copy text-muted"></i>
        {{ 'article.name_plural'|trans }}
        ({{ items.getTotalItemCount }})
    </h1>

    {% if items|length == 0 %}
        <div class="alert alert-warning">{{ 'common.list_is_empty'|trans }}</div>
    {% else %}
        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>{{ knp_pagination_sortable(items, 'article.title'|trans, 't.content') }}</th>
                    {#<th class="col-lg-6">{{ 'article.title'|trans }}</th>#}
                    <th>{{ 'article.authors'|trans }}</th>
                    <th>{{ knp_pagination_sortable(items, 'common.created_at'|trans, 'a.createdAt') }}</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>

            <tbody>

                {% for i in items %}
                    <tr>
                        <td>
                            <a class="badge" href="{{ path('article.item', { id: i.id }) }}">
                                {{ i.id }}
                            </a>
                        </td>
                        <td>{{ i.translate(app.request.locale).title }}</td>
                        <td class="text-muted"><em>
                                {% for a in i.authors %}
                                    {{ a }}<br/>
                                {% endfor %}</em>
                        </td>
                        <td>{{ i.createdAt|date('Y-m-d H:i') }}</td>
                        <td>
                            <a class="btn btn-default btn-xs" href="{{ path('article.item', { id: i.id }) }}">
                                <i class="fa fa-eye fa-lg"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>

        {{ knp_pagination_render(items) }}

    {% endif %}

{% endblock %}